import '../globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';
import { StyledEngineProvider } from '@mui/material';
import { UserProvider } from '@auth0/nextjs-auth0/client';
import Header from '../components/Header/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <StyledEngineProvider injectFirst>
        <UserProvider>
          <body className={inter.className}>
            <Header />
            {children}
          </body>
        </UserProvider>
      </StyledEngineProvider>
    </html>
  );
}
